import esbuild from "esbuild";
import process from "process";
import fs from 'fs';
import path from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = (process.argv[2] === 'production');

const ctx = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: {
		main: 'plugin/main.ts',
		'crypto.worker': 'plugin/crypto.worker.ts'
	},
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr'
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	minify: prod,
	outdir: 'uwu-crypt',
	plugins: [
		{
			name: 'copy-files',
			setup(build) {
				build.onEnd(() => {
					if (!fs.existsSync('uwu-crypt')) {
						fs.mkdirSync('uwu-crypt');
					}
					fs.copyFileSync(path.resolve('pkg/uwu_crypt_bg.wasm'), path.resolve('uwu-crypt/uwu_crypt_bg.wasm'));
					fs.copyFileSync(path.resolve('manifest.json'), path.resolve('uwu-crypt/manifest.json'));
					if (fs.existsSync('styles.css')) {
						fs.copyFileSync(path.resolve('styles.css'), path.resolve('uwu-crypt/styles.css'));
					}
				});
			},
		},
	],
});

if (prod) {
	await ctx.rebuild();
	process.exit(0);
} else {
	await ctx.watch();
}
